"""add flights route search index

Revision ID: 2b19d14b47a1
Revises: 32fa4a159ffc
Create Date: 2026-10-07 21:58:25.086039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b19d14b47a1'
down_revision: Union[str, Sequence[str], None] = '32fa4a159ffc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_flights_route_start_time', 'flights', ['departure_airport', 'arrival_airport', 'start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # The upgrade made MySQL silently drop the foreign key's own index on
    # departure_airport, because the new index starts with that column. The
    # foreign key now depends on the new index, and MySQL refuses to drop it
    # until a replacement exists.
    op.create_index('departure_airport', 'flights', ['departure_airport'])
    op.drop_index('ix_flights_route_start_time', table_name='flights')
