"""add booking idempotency key

Revision ID: 32fa4a159ffc
Revises: 5eb08213c3df
Create Date: 2026-10-07 21:12:49.870357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32fa4a159ffc'
down_revision: Union[str, Sequence[str], None] = '5eb08213c3df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('idempotency_key', sa.String(length=64), nullable=True))
    op.create_unique_constraint('uq_bookings_user_id_idempotency_key', 'bookings', ['user_id', 'idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # The upgrade made MySQL silently drop the foreign key's own index on
    # user_id (the new unique index covers user_id, so it was redundant). The
    # foreign key now depends on the unique index, and MySQL refuses to drop it
    # ("needed in a foreign key constraint") unless a replacement exists first.
    op.create_index('user_id', 'bookings', ['user_id'])
    op.drop_constraint('uq_bookings_user_id_idempotency_key', 'bookings', type_='unique')
    op.drop_column('bookings', 'idempotency_key')
