"""fix bookings columns and add payments table

Revision ID: 3dd98db2b018
Revises: eaeba85ad321
Create Date: 2026-09-29 22:15:49.168742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3dd98db2b018'
down_revision: Union[str, Sequence[str], None] = 'eaeba85ad321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', name='paymentstatus', native_enum=False, length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    op.add_column('bookings', sa.Column('seats_booked', sa.Integer(), nullable=False))
    op.add_column('bookings', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('bookings', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('bookings', 'status',
               existing_type=mysql.VARCHAR(length=9),
               type_=sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', name='bookingstatus', native_enum=False, length=20),
               existing_nullable=False)
    op.drop_column('bookings', 'num_of_seats')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('num_of_seats', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('bookings', 'status',
               existing_type=sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', name='bookingstatus', native_enum=False, length=20),
               type_=mysql.VARCHAR(length=9),
               existing_nullable=False)
    op.drop_column('bookings', 'updated_at')
    op.drop_column('bookings', 'created_at')
    op.drop_column('bookings', 'seats_booked')
    op.drop_table('payments')
    # ### end Alembic commands ###
