"""add airline_name index

Revision ID: 5eb08213c3df
Revises: 3dd98db2b018
Create Date: 2026-10-07 15:56:50.953365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eb08213c3df'
down_revision: Union[str, Sequence[str], None] = '3dd98db2b018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_flights_airline_name'), 'flights', ['airline_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flights_airline_name'), table_name='flights')
    # ### end Alembic commands ###
